'use client';
import { Inter } from 'next/font/google';
// import { getServerSession } from 'next-auth/react';
// import { authOptions } from '../../pages/api/auth/[...nextauth]';
import { SessionProvider } from 'next-auth/react';

import './globals.css';
import Navbar from './component/navbar';
import Footer from './component/footer';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SessionProvider session={session}>{children}</SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
